{!! $intro !!}

=========================================================
{!! $projectTitle !!}
Submitted {!! $submitted !!}
=========================================================

View this {!! $reportType !!} here:

{!! $url !!}


------------

This email notification was generated by the University of Washington, College
of the Environment's {!! $appName !!}. If you have trouble with this
notification or have received this message in error, please contact the college
Help Desk at itreq@uw.edu.
